version: '3'
services:
  interviewer:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    ports:
    - "8002:8000"
    command: "python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
