version: '3'
services:
  interviewer:
    build:
      context: '.'
      dockerfile: './Dockerfile'
    ports:
    - "${PORT}:8000"
    command: "python -m uvicorn interviewer.main:app --reload --host 0.0.0.0 --port 8000"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  nginx:
    image: "nginx:1.21.4-alpine"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: "certbot/certbot"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot